language: python
python:
  - "2.7"

notifications:
  email: false
sudo: false

os:
  - linux
  - osx

install:
  - pip install --upgrade pip setuptools wheel
  - pip install --only-binary=numpy,scipy numpy scipy matplotlib
  - python setup.py install

script:
  - python ./test/test_orthopoly.py
  - python ./test/test_domain_algebraic_decay
  - python ./test/test_orthopoly.py
  - python ./examples/poisson.py
  - python ./examples/poisson_vec.py
